
import React from 'react';
import { TRANSLATIONS } from '../translations';

interface DoctorSummaryModalProps {
  summary: string;
  onClose: () => void;
  langCode?: string;
}

declare global {
  interface Window {
    jspdf: any;
  }
}

export const DoctorSummaryModal: React.FC<DoctorSummaryModalProps> = ({ summary, onClose, langCode = 'en' }) => {
  const t = TRANSLATIONS[langCode] || TRANSLATIONS['en'];

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
  };

  const handleDownloadPDF = () => {
    if (!window.jspdf) {
        alert("PDF generator not loaded yet. Please try again in a moment.");
        return;
    }

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(0, 0, 210, 20, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("MediGuide AI - Pre-Consultation Report", 10, 13);
    
    // Content Configuration
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    
    const pageHeight = doc.internal.pageSize.height;
    const margin = 10;
    let cursorY = 30;

    // Disclaimer
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text("DISCLAIMER: This report is generated by AI and is not an official medical record.", margin, cursorY);
    cursorY += 10;
    doc.text("Please present this summary to a healthcare professional.", margin, cursorY);
    cursorY += 15;

    // Body text (Split by newlines to handle formatting slightly better in raw PDF)
    doc.setFontSize(11);
    doc.setTextColor(0);
    
    // Simple word wrap
    const textLines = doc.splitTextToSize(summary, 190);
    
    // Iterate and print
    textLines.forEach((line: string) => {
        if (cursorY > pageHeight - 20) {
            doc.addPage();
            cursorY = 20;
        }
        
        // Simple check for Headers in markdown style
        if (line.startsWith('#') || line.startsWith('###')) {
             doc.setFont("helvetica", "bold");
             doc.text(line.replace(/#/g, '').trim(), margin, cursorY);
             doc.setFont("helvetica", "normal");
        } else {
             doc.text(line, margin, cursorY);
        }
        cursorY += 7;
    });

    // Save
    doc.save("MediGuide_Report.pdf");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl flex flex-col max-h-[90vh] animate-in fade-in zoom-in duration-200">
        <div className="p-6 border-b border-gray-200 flex justify-between items-center bg-gray-50 rounded-t-xl">
           <div className="flex items-center space-x-3">
              <div className="bg-indigo-600 p-2 rounded-lg text-white">
                 <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                 </svg>
              </div>
              <h2 className="text-xl font-bold text-gray-900">{t.actions.report}</h2>
           </div>
           <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
             <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
           </button>
        </div>
        
        <div className="p-8 overflow-y-auto flex-1 bg-white">
           <div className="prose prose-indigo max-w-none font-sans text-sm text-gray-800 leading-relaxed whitespace-pre-wrap">
              {summary}
           </div>
        </div>

        <div className="p-6 border-t border-gray-200 bg-gray-50 rounded-b-xl flex justify-between items-center">
           <p className="text-xs text-gray-500 italic hidden sm:block">Generated by AI. Not a medical record.</p>
           <div className="flex space-x-3 w-full sm:w-auto justify-end">
              <button onClick={handleCopy} className="px-4 py-2 bg-white border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors shadow-sm flex items-center font-medium">
                 <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                 {t.actions.copy}
              </button>
              <button onClick={handleDownloadPDF} className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors shadow-sm flex items-center font-medium">
                 <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" /></svg>
                 Download PDF
              </button>
           </div>
        </div>
      </div>
    </div>
  );
};
